plt.figure(figsize=(6, 4))
plt.plot(thresholds, precisions, marker="o", label="precision")
plt.plot(thresholds, recalls, marker="o", label="recall")
plt.xlabel("Decision threshold")
plt.ylabel("Score")
plt.title("Threshold policy changes precision and recall")
plt.legend()
plt.tight_layout()
plt.show()
