plt.figure(figsize=(6, 4))
plt.hist(anomaly_score[y_test.to_numpy() == 0], bins=30, alpha=0.65, label="non-fraud")
plt.hist(anomaly_score[y_test.to_numpy() == 1], bins=30, alpha=0.65, label="fraud")
plt.xlabel("Anomaly score")
plt.ylabel("Transactions")
plt.title("Isolation Forest score distribution")
plt.legend()
plt.tight_layout()
plt.show()
