plt.figure(figsize=(6, 4))
plt.plot(label_counts, active_val_scores, marker="o", label="uncertainty sampling")
plt.plot(label_counts, random_val_scores, marker="o", label="random querying")
plt.xlabel("Number of labeled pool examples")
plt.ylabel("Validation accuracy")
plt.title("Label efficiency during development")
plt.legend()
plt.tight_layout()
plt.show()
