plt.figure(figsize=(8, 4))
plt.plot(dates_valid, y_valid.to_numpy(), label="actual")
plt.plot(dates_valid, pred, label="predicted")
plt.xlabel("Date")
plt.ylabel("Daily rentals")
plt.title("Chronological validation: actual versus predicted demand")
plt.legend()
plt.tight_layout()
plt.show()
